package bot.state.movement

// AUTO-GENERATED by train_move_predictor.py — do not edit by hand.
// Trained from movement JSON data. Lookup key: (action, objGridOffset,
// objInputDir, objDir, objPosFrac).  objQSpeedFrac=96, linkGoStraight=0
// are assumed constant (only value observed in training data).
//
// Targets: dist, newObjGridOffset, newObjPosFrac, deltaX, deltaY

data class MovePrediction(
    val dist: Int,
    val newObjGridOffset: Int,
    val newObjPosFrac: Int,
    val deltaX: Int,
    val deltaY: Int,
) {
    companion object {
        val UNKNOWN = MovePrediction(0, 0, 0, 0, 0)
    }
}

object MovePredictorData {
    /**
     * Look up movement prediction from physics state.
     *
     * @param action     GamePad action encoded as Int (0=None,1=Right,2=Left,4=Down,8=Up)
     * @param gridOffset objGridOffset (signed, -8..8)
     * @param inputDir   objInputDir bitmask (0,1,2,4,8)
     * @param objDir     objDir bitmask (1,2,4,8)
     * @param posFrac    objPosFrac (0..255)
     */
    fun lookup(action: Int, gridOffset: Int, inputDir: Int, objDir: Int, posFrac: Int): MovePrediction {
        return table[key(action, gridOffset, inputDir, objDir, posFrac)]
            ?: MovePrediction.UNKNOWN
    }

    private fun key(a: Int, g: Int, i: Int, d: Int, p: Int): Long =
        ((a.toLong() and 0xFF) shl 40) or
        ((g.toLong() and 0xFF) shl 32) or
        ((i.toLong() and 0xFF) shl 24) or
        ((d.toLong() and 0xFF) shl 16) or
        ((p.toLong() and 0xFFFF))

    private val table: Map<Long, MovePrediction> = buildMap {
        put(key(0, -7, 0, 2, 0), MovePrediction(0, -7, 0, 0, 0))  // action=None
        put(key(0, -7, 0, 2, 128), MovePrediction(1, 0, 0, -1, 0))  // action=None
        put(key(0, -7, 0, 8, 0), MovePrediction(0, -7, 0, 0, 0))  // action=None
        put(key(0, -6, 0, 1, 128), MovePrediction(2, -4, 0, 2, 0))  // action=None
        put(key(0, -6, 0, 2, 128), MovePrediction(1, -7, 0, -1, 0))  // action=None
        put(key(0, -6, 0, 8, 0), MovePrediction(0, -6, 0, 0, 0))  // action=None
        put(key(0, -6, 0, 8, 128), MovePrediction(1, -7, 0, 0, -1))  // action=None
        put(key(0, -5, 0, 8, 128), MovePrediction(1, -6, 0, 0, -1))  // action=None
        put(key(0, -4, 0, 1, 0), MovePrediction(0, -4, 0, 0, 0))  // action=None
        put(key(0, -4, 0, 8, 0), MovePrediction(0, -4, 0, 0, 0))  // action=None
        put(key(0, -3, 0, 1, 128), MovePrediction(2, -1, 0, 2, 0))  // action=None
        put(key(0, -3, 0, 8, 0), MovePrediction(0, -3, 0, 0, 0))  // action=None
        put(key(0, -3, 0, 8, 128), MovePrediction(1, -4, 0, 0, -1))  // action=None
        put(key(0, -2, 0, 8, 128), MovePrediction(1, -3, 0, 0, -1))  // action=None
        put(key(0, -1, 0, 1, 0), MovePrediction(0, -1, 0, 0, 0))  // action=None
        put(key(0, -1, 0, 8, 0), MovePrediction(0, -1, 0, 0, 0))  // action=None
        put(key(0, 0, 0, 1, 0), MovePrediction(0, 0, 0, 0, 0))  // action=None
        put(key(0, 0, 0, 1, 128), MovePrediction(2, 2, 0, 2, 0))  // action=None
        put(key(0, 0, 0, 2, 0), MovePrediction(0, 0, 0, 0, 0))  // action=None
        put(key(0, 0, 0, 2, 128), MovePrediction(1, -1, 0, 0, -1))  // action=None
        put(key(0, 0, 0, 8, 128), MovePrediction(1, -1, 0, 0, -1))  // action=None
        put(key(0, 1, 0, 1, 128), MovePrediction(2, 3, 0, 2, 0))  // action=None
        put(key(0, 2, 0, 1, 0), MovePrediction(0, 2, 0, 0, 0))  // action=None
        put(key(0, 3, 0, 1, 0), MovePrediction(0, 3, 0, 0, 0))  // action=None
        put(key(0, 3, 0, 1, 128), MovePrediction(2, 5, 0, 2, 0))  // action=None
        put(key(0, 4, 0, 1, 128), MovePrediction(2, 6, 0, 2, 0))  // action=None
        put(key(0, 5, 0, 1, 0), MovePrediction(0, 5, 0, 0, 0))  // action=None
        put(key(0, 6, 0, 1, 0), MovePrediction(0, 6, 0, 0, 0))  // action=None
        put(key(0, 6, 0, 1, 128), MovePrediction(2, 0, 0, 2, 0))  // action=None
        put(key(0, 7, 0, 1, 128), MovePrediction(1, 0, 0, 1, 0))  // action=None
        put(key(1, -4, 1, 4, 0), MovePrediction(1, -3, 128, 0, 1))  // action=MoveRight
        put(key(1, -4, 1, 8, 0), MovePrediction(2, -6, 128, 0, -2))  // action=MoveRight
        put(key(1, -3, 1, 4, 128), MovePrediction(2, -1, 0, 0, 2))  // action=MoveRight
        put(key(1, -3, 1, 8, 128), MovePrediction(1, -4, 0, 0, -1))  // action=MoveRight
        put(key(1, -1, 1, 4, 0), MovePrediction(1, 0, 128, 0, 1))  // action=MoveRight
        put(key(1, -1, 1, 8, 0), MovePrediction(1, 0, 128, 0, 1))  // action=MoveRight
        put(key(1, 0, 1, 1, 0), MovePrediction(1, 1, 128, 1, 0))  // action=MoveRight
        put(key(1, 0, 1, 4, 128), MovePrediction(2, 2, 0, 2, 0))  // action=MoveRight
        put(key(1, 1, 1, 1, 128), MovePrediction(2, 3, 0, 2, 0))  // action=MoveRight
        put(key(1, 2, 1, 1, 0), MovePrediction(1, 3, 128, 1, 0))  // action=MoveRight
        put(key(1, 3, 1, 1, 0), MovePrediction(1, 4, 128, 1, 0))  // action=MoveRight
        put(key(1, 3, 1, 1, 128), MovePrediction(2, 5, 0, 2, 0))  // action=MoveRight
        put(key(1, 4, 1, 1, 128), MovePrediction(2, 6, 0, 2, 0))  // action=MoveRight
        put(key(1, 5, 1, 1, 0), MovePrediction(1, 6, 128, 1, 0))  // action=MoveRight
        put(key(1, 6, 1, 1, 0), MovePrediction(1, 7, 128, 1, 0))  // action=MoveRight
        put(key(1, 6, 1, 1, 128), MovePrediction(2, 0, 0, 2, 0))  // action=MoveRight
        put(key(1, 7, 1, 1, 128), MovePrediction(1, 0, 0, 1, 0))  // action=MoveRight
        put(key(2, -7, 2, 2, 0), MovePrediction(1, 0, 128, -1, 0))  // action=MoveLeft
        put(key(2, -6, 2, 2, 0), MovePrediction(2, 0, 128, -2, 0))  // action=MoveLeft
        put(key(2, -6, 2, 2, 128), MovePrediction(1, -7, 0, -1, 0))  // action=MoveLeft
        put(key(2, -5, 2, 2, 128), MovePrediction(1, -6, 0, -1, 0))  // action=MoveLeft
        put(key(2, -4, 2, 2, 0), MovePrediction(2, -6, 128, -2, 0))  // action=MoveLeft
        put(key(2, -3, 2, 2, 0), MovePrediction(2, -5, 128, -2, 0))  // action=MoveLeft
        put(key(2, -3, 2, 2, 128), MovePrediction(1, -4, 0, -1, 0))  // action=MoveLeft
        put(key(2, -3, 2, 8, 0), MovePrediction(1, 6, 128, 0, 1))  // action=MoveLeft
        put(key(2, -2, 2, 2, 128), MovePrediction(1, -3, 0, -1, 0))  // action=MoveLeft
        put(key(2, -2, 2, 8, 128), MovePrediction(1, -3, 0, 0, -1))  // action=MoveLeft
        put(key(2, -1, 2, 2, 0), MovePrediction(2, -3, 128, -2, 0))  // action=MoveLeft
        put(key(2, 0, 2, 2, 128), MovePrediction(1, -1, 0, -1, 0))  // action=MoveLeft
        put(key(2, 0, 2, 4, 0), MovePrediction(2, -2, 128, -2, 0))  // action=MoveLeft
        put(key(2, 0, 2, 8, 0), MovePrediction(2, -2, 128, -2, 0))  // action=MoveLeft
        put(key(2, 6, 2, 4, 128), MovePrediction(2, 0, 0, 0, 2))  // action=MoveLeft
        put(key(4, -7, 4, 8, 0), MovePrediction(1, -6, 128, 0, 1))  // action=MoveDown
        put(key(4, -6, 4, 4, 128), MovePrediction(2, -4, 0, 0, 2))  // action=MoveDown
        put(key(4, -6, 4, 8, 128), MovePrediction(1, -7, 0, 0, -1))  // action=MoveDown
        put(key(4, -3, 4, 8, 0), MovePrediction(1, -2, 128, 0, 1))  // action=MoveDown
        put(key(4, -2, 4, 4, 128), MovePrediction(2, 0, 0, 0, 2))  // action=MoveDown
        put(key(4, -2, 4, 8, 128), MovePrediction(1, -3, 0, 0, -1))  // action=MoveDown
        put(key(4, 0, 4, 4, 0), MovePrediction(1, 1, 128, 0, 1))  // action=MoveDown
        put(key(4, 1, 4, 4, 128), MovePrediction(2, 3, 0, 0, 2))  // action=MoveDown
        put(key(4, 3, 4, 4, 0), MovePrediction(1, 4, 128, 0, 1))  // action=MoveDown
        put(key(4, 4, 4, 4, 128), MovePrediction(2, 6, 0, 0, 2))  // action=MoveDown
        put(key(4, 6, 4, 4, 0), MovePrediction(1, 7, 128, 0, 1))  // action=MoveDown
        put(key(4, 7, 4, 4, 128), MovePrediction(1, 0, 0, 0, 1))  // action=MoveDown
        put(key(8, -7, 8, 2, 0), MovePrediction(1, 0, 128, -1, 0))  // action=MoveUp
        put(key(8, -7, 8, 8, 0), MovePrediction(1, 0, 128, 0, -1))  // action=MoveUp
        put(key(8, -6, 8, 8, 128), MovePrediction(1, -7, 0, 0, -1))  // action=MoveUp
        put(key(8, -4, 8, 8, 0), MovePrediction(2, -6, 128, 0, -2))  // action=MoveUp
        put(key(8, -3, 8, 8, 128), MovePrediction(1, -4, 0, 0, -1))  // action=MoveUp
        put(key(8, -1, 8, 8, 0), MovePrediction(2, -3, 128, 0, -2))  // action=MoveUp
        put(key(8, 0, 8, 1, 0), MovePrediction(2, -2, 128, 0, -2))  // action=MoveUp
        put(key(8, 0, 8, 2, 128), MovePrediction(1, -1, 0, 0, -1))  // action=MoveUp
        put(key(8, 0, 8, 4, 0), MovePrediction(2, -2, 128, 0, -2))  // action=MoveUp
        put(key(8, 0, 8, 8, 128), MovePrediction(1, -1, 0, 0, -1))  // action=MoveUp
    }
}
